services:
  kobold:
    build: .
    container_name: kobold
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      # Watch directory (mount your books folder here)
      - ./books:/books
    environment:
      - KB_WATCH_DIRS=/books
      - KB_LOG_LEVEL=INFO
      - KB_USER_TOKEN=<INSERT_GENERATED_TOKEN_HERE>
    env_file:
      - .env
